---
- name: Ensure AD user exists in a specified OU and is part of specific groups
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Ensure user bob is present in OU ou=xxx,dc=xxx,dc=xxx
      microsoft.ad.user:
        identity: "{{ user_identity }}"          
        password: "{{ user_password }}"          
        state: present
        path: ou=Technik,dc=arrowlab,dc=local
        groups:
          set:
            - Arrowlab-Users
 
