---
- name: Prepare hosts for being automated by Ansible
  hosts: all
  become: yes

  tasks:
    - name: Ensure ansible user is configured
      ansible.builtin.user:
        name: ansible
        state: absent
        createhome: yes
        shell: /bin/bash

    - name: Allow ansible to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Remove ansible-host1 user
      ansible.builtin.user:
        name: ansible-host1
        state: absent
        remove: yes
        force: yes

    - name: Confirm setup completion
      debug:
        msg: "Ansible user configured and ansible-host1 user deleted successfully."
