---
- name: Create a subfolder under VM folder on given datacenter
  hosts: localhost
  become: false
  gather_facts: false

  
  tasks:
    - name: Create subfolder under VM folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false  # Set to true if you want to validate SSL certificates
        datacenter: "{{ vcenter_datacenter_name }}"
        folder: "{{ parent_folder }}/{{ sub_folder_name }}"
        state: present
      register: sub_folder_creation_result
      delegate_to: localhost

    - name: Display confirmation message
      debug:
        msg: "Subfolder '{{ sub_folder_name }}' has been successfully created under '{{ parent_folder }}' in datacenter '{{ vcenter_datacenter_name }}'."
      
