- name: Create Folder for Onboarding User
  hosts: localhost
  become: false
  gather_facts: false
  
  tasks:
    - name: Create folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: vm
        state: present
        parent_folder: "User"

    - name: Debug folder creation message
      debug:
        msg: "Folder '{{ vcenter_destination_folder }}' created successfully in datacenter '{{ vcenter_datacenter }}'"
