---
- name: Create VM on vSphere
  hosts: localhost
  become: false
  gather_facts: true
  tasks:
    - name: create VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        template: "{{ vm_template }}"
        name: "{{ vm_name }}"
        folder: "{{ vcenter_destination_folder }}"
        state: "{{ vm_state }}"
        cluster: "{{ vcenter_cluster }}"
        resource_pool: "{{ vcenter_resource_pool }}"
        disk:
          - size_gb: "{{ vm_disk_gb }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
        hardware:
          memory_mb: "{{ vm_hw_ram_mb }}"
          num_cpus: "{{ vm_hw_cpu_n }}"
          scsi: "{{ vm_hw_scsi }}"
          hotadd_cpu: "{{ hot_add_cpu | default('True') }}"
          hotadd_memory: "{{ hot_add_memory | default('True') }}"

    - name: Display success message when the VM is deployed
      debug:
        msg: "The VM '{{ vm_name }}' has been successfully deployed in folder '{{ vcenter_destination_folder }}'."
