---
- name: Delete all completed pods in all namespaces
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Delete completed pods in all namespaces
      redhat.openshift.k8s:
        state: absent
        namespace: "*"
        selector: status=Completed
