---
- name: Install LAMP Stack
  hosts: all
  become: true
  tasks:
   # - name: Open necessary ports for Apache
   #   firewalld:
   #     port: 80/tcp
   #     permanent: true
   #     state: enabled

    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Start Apache and enable it on boot
      service:
        name: httpd
        state: started
        enabled: true

    - name: Open necessary ports for MySQL
      firewalld:
        port: 3306/tcp
        permanent: true
        state: enabled

    - name: Install MySQL
      package:
        name: mysql-server
        state: present

    - name: Start MySQL and enable it on boot
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Install PHP
      package:
        name: php
        state: present

    - name: Restart Apache to apply PHP changes
      service:
        name: httpd
        state: restarted
