---
- name: Change address
  hosts: Fortigate-Ansible-Demo
  gather_facts: no

  tasks:
    - name: Create Address
      fortinet.fortios.fortios_firewall_address:
        access_token: "{{ ansible_password }}"
        state: "present"
        firewall_address:
          name: '{{ address_name }}'
          subnet: "{{ subnet }}"

    - name: Debug message after address creation
      debug:
        msg: "Address '{{ address_name }}' with subnet '{{ subnet }}' has been successfully created or updated."
