---
- name: Change address
  hosts: MAWE-Fortigate-test
  connection: httpapi
  gather_facts: no

  tasks:
    - name: Create Address
      fortinet.fortios.fortios_firewall_address:
        access_token: "{{ ansible_password }}"
        state: "present"
        firewall_address:
          name: "test_123"
          subnet: "10.1.1.1/24"

    - name: Debug message after address creation
      debug:
        msg: "Address 'test_123' with subnet '10.1.1.1/24' has been successfully created or updated."
