---
- name: Change address
  hosts: Fortigate Inventory
  connection: httpapi
  gather_facts: no

  tasks:
    - name: Create Address
      fortinet.fortios.fortios_firewall_address:
        access_token: "{{ ansible_password }}"
        state: "present"
        firewall_address:
          name: "test_123"
          subnet: "10.1.1.1/24"

  
