---
- name: Prepare hosts for being automated by Ansible
  hosts: all
  become: yes

  tasks:
    - name: Ensure ansible user is configured
      ansible.builtin.user:
        name: ansible
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Allow ansible to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Confirm setup completion
      debug:
        msg: "Ansible user configuration and passwordless sudo setup completed successfully."
