---
- name: Register system with Red Hat Subscription Manager and Insights using email/password
  hosts: all
  become: true

  tasks:
    - name: Set system keyboard layout to German (de)
      hosts: all
      become: true

    - name: Set keyboard layout to German
      command: localectl set-keymap de
      changed_when: false   # Since localectl does not provide output on success, we assume no change

    - name: Ensure Subscription Manager is installed
      yum:
        name: subscription-manager
        state: present

    - name: Ensure Insights client is installed
      yum:
        name: insights-client
        state: present

    - name: Register the system with Red Hat Subscription Manager using email and password
      command: >
        subscription-manager register --username "{{ rhsm_user }}" --password "{{ rhsm_password }}"
      register: rhsm_register
      failed_when: "'already registered' not in rhsm_register.stderr"
      changed_when: "'The system has been registered with ID' in rhsm_register.stdout"

    - name: Ensure system is registered with Insights
      command: insights-client --register
      register: insights_register
      changed_when: "'Insights successfully registered' in insights_register.stdout or 'Machine already registered' in insights_register.stdout"

    - name: Display status of Insights registration
      debug:
        msg: "Insights registration status: {{ insights_register.stdout }}"
