---
- name: Register system with Red Hat Subscription Manager and Insights using email/password
  hosts: all
  become: true
  gather_facts: true

  tasks:
   
    - name: Ensure Subscription Manager is installed
      yum:
        name: subscription-manager
        state: present

    - name: Ensure Insights client is installed
      yum:
        name: insights-client
        state: present

    - name: Register the system with Red Hat Subscription Manager using email and password
      command: >
        subscription-manager register --username "{{ rhsm_user }}" --password "{{ rhsm_password }}"
      register: rhsm_register
      failed_when: "'already registered' not in rhsm_register.stderr"
      changed_when: "'The system has been registered with ID' in rhsm_register.stdout"
