---
- name: Create a Resource Pool in VMware
  hosts: localhost
  become: false
  gather_facts: true


  tasks:
    - name: Create Resource Pool
      community.vmware.vmware_resource_pool:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        resource_pool: '{{ resource_pool_name }}'
        state: present
      register: resource_pool_creation_result

    - name: Display confirmation message
      debug:
        msg: "Resource Pool '{{ resource_pool_name }}' created successfully in datacenter '{{ vcenter_datacenter }}'."
      when: resource_pool_creation_result is changed  # Only show if the resource pool was created
