---
- name: Apache Webserver configuration on Ubuntu
  hosts: all
  become: true

  tasks:

    - name: Update System and packages upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Apache
      apt:
        name: apache2
        state: present

    

    - name: Automated index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
            <title>{{ title_response.response }}</title>
            <style>
              body { font-family: Arial, sans-serif; background-color: #f4f4f9; color: #333; text-align: center; margin-top: 50px; }
              h1 { color: #336699; }
              p { font-size: 1.1em; line-height: 1.6em; }
              .footer { margin-top: 40px; font-size: 0.9em; color: #666; }
            </style>
          </head>
          <body>
            <h1>{{ title_response.response }}</h1>
            <p>{{ content_response.response }}</p>
            <div class="footer">
              <p>Server administriert durch Ansible | Erstellt am {{ ansible_date_time.date }}</p>
            </div>
          </body>
          </html>
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
