---
- name: Deploy a new VMware Port Group
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a new port group with static port binding
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vcenter_hostname }}"
        validate_certs: no
        switch_name: "{{ switch_name}}"
        portgroup_name: "{{ portgroup_name }}"
        vlan_id: "{{ vlan_id }}"
        port_binding: "static"  # Set port binding to static
        state: present
      delegate_to: localhost

    - name: Display success message when the port group is deployed
      debug:
        msg: "The port group '{{ portgroup_name }}' has been successfully deployed on switch '{{ switch_name }}'."
